FROM registry.redhat.io/rhai/base-image-cpu-rhel9:3.4.0-1777399554

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src
COPY prompts.json ./

ENV HOST=0.0.0.0
ENV PORT=8004
EXPOSE 8004

CMD ["python", "-m", "src"]
