FROM registry.redhat.io/rhai/base-image-cpu-rhel9:3.4.0

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src

ENV HOST=0.0.0.0
ENV PORT=9100
EXPOSE 9100

CMD ["python", "-m", "src"]
