"""nn.Module definitions for the 3-stage SKU extraction pipeline: localize,
orient, read. All three are small (this trains fine on CPU/MPS for a
few-thousand-image synthetic dataset) - the point of these notebooks is the
pipeline, not squeezing out state-of-the-art accuracy per stage.
"""

from __future__ import annotations

import torch
from torch import nn

# SKUs generated by label-generator-api are always upper-cased (see
# `_validate_sku`), so the charset only needs to cover what that generator can
# actually produce. Index 0 is reserved for the CTC blank symbol.
OCR_CHARSET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-"
BLANK_IDX = 0
CHAR_TO_IDX = {char: idx + 1 for idx, char in enumerate(OCR_CHARSET)}
IDX_TO_CHAR = {idx: char for char, idx in CHAR_TO_IDX.items()}
NUM_CLASSES = len(OCR_CHARSET) + 1  # + blank


def _conv_block(in_channels: int, out_channels: int, pool: tuple[int, int] | int | None = 2) -> nn.Sequential:
    layers = [
        nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1),
        nn.BatchNorm2d(out_channels),
        nn.ReLU(inplace=True),
    ]
    if pool is not None:
        layers.append(nn.MaxPool2d(pool))
    return nn.Sequential(*layers)


class LocalizerNet(nn.Module):
    """Full raw photo (resized to INPUT_SIZE x INPUT_SIZE) -> normalized
    (xmin, ymin, xmax, ymax) bbox of the sticker, per `geometry.normalize_bbox`."""

    INPUT_SIZE = 224

    def __init__(self) -> None:
        super().__init__()
        self.features = nn.Sequential(
            _conv_block(3, 16),
            _conv_block(16, 32),
            _conv_block(32, 64),
            _conv_block(64, 128),
            _conv_block(128, 128),
        )
        self.head = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Linear(128, 64),
            nn.ReLU(inplace=True),
            nn.Linear(64, 4),
            nn.Sigmoid(),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.head(self.features(x))


class OrientationNet(nn.Module):
    """Padded sticker crop (resized to INPUT_SIZE x INPUT_SIZE) -> unit
    (sin, cos) of the rotation angle, per `geometry.angle_to_sin_cos`."""

    INPUT_SIZE = 128

    def __init__(self) -> None:
        super().__init__()
        self.features = nn.Sequential(
            _conv_block(3, 16),
            _conv_block(16, 32),
            _conv_block(32, 64),
            _conv_block(64, 128),
        )
        self.head = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Linear(128, 32),
            nn.ReLU(inplace=True),
            nn.Linear(32, 2),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        out = self.head(self.features(x))
        return out / out.norm(dim=1, keepdim=True).clamp_min(1e-6)


class CRNNReader(nn.Module):
    """Upright sticker crop (resized to HEIGHT x WIDTH) -> per-timestep
    log-probabilities over `OCR_CHARSET` + blank, for `nn.CTCLoss` /
    `greedy_ctc_decode`."""

    HEIGHT = 32
    WIDTH = 160

    def __init__(self, num_classes: int = NUM_CLASSES, rnn_hidden: int = 128) -> None:
        super().__init__()
        self.cnn = nn.Sequential(
            _conv_block(3, 32, pool=2),   # H/2, W/2
            _conv_block(32, 64, pool=2),  # H/4, W/4
            _conv_block(64, 128, pool=(2, 1)),  # H/8, W/4 - keep width resolution for the sequence dim
            _conv_block(128, 128, pool=None),
        )
        # HEIGHT=32 -> two /2 pools + one (2,1) pool collapse height to 32/2/2/2 = 4.
        collapsed_height = self.HEIGHT // 8
        self.rnn = nn.LSTM(128 * collapsed_height, rnn_hidden, num_layers=2, bidirectional=True, batch_first=True)
        self.classifier = nn.Linear(rnn_hidden * 2, num_classes)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        features = self.cnn(x)  # (B, C, H', W')
        b, c, h, w = features.shape
        features = features.permute(0, 3, 1, 2).reshape(b, w, c * h)  # (B, W', C*H') - sequence over width
        rnn_out, _ = self.rnn(features)
        logits = self.classifier(rnn_out)  # (B, W', num_classes)
        log_probs = logits.log_softmax(dim=2)
        return log_probs.permute(1, 0, 2)  # (T, B, num_classes) - nn.CTCLoss's expected layout


def greedy_ctc_decode(log_probs: torch.Tensor) -> list[str]:
    """Best-path greedy CTC decode: `log_probs` is (T, B, num_classes)."""
    best_path = log_probs.argmax(dim=2).transpose(0, 1)  # (B, T)
    decoded = []
    for sequence in best_path.tolist():
        chars = []
        previous = None
        for idx in sequence:
            if idx != BLANK_IDX and idx != previous:
                chars.append(IDX_TO_CHAR[idx])
            previous = idx
        decoded.append("".join(chars))
    return decoded
