{{- $svcName := include "adc.distributionCenter.serviceName" (dict "root" $ "component" "dc-agent") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svcName }}
  labels:
    {{- include "adc.commonLabels" . | nindent 4 }}
    app.kubernetes.io/name: dc-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: dc-agent
spec:
  selector:
    app.kubernetes.io/name: dc-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.dcAgent.port }}
      targetPort: http
