{{- $svcName := include "adc.distributionCenter.serviceName" (dict "root" $ "component" "dc-agent") }}
{{- if and .Values.global.openshift.routes.enabled .Values.dcAgent.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $svcName }}
  labels:
    {{- include "adc.commonLabels" . | nindent 4 }}
    app.kubernetes.io/name: dc-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: dc-agent
spec:
  to:
    kind: Service
    name: {{ $svcName }}
  port:
    targetPort: http
  tls:
    termination: {{ .Values.global.openshift.routes.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.global.openshift.routes.tls.insecureEdgeTerminationPolicy }}
{{- end }}
