{{- $cmName := printf "%s-robot-shelves" (include "adc.fullname" $) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cmName }}
  labels:
    {{- include "adc.commonLabels" . | nindent 4 }}
    app.kubernetes.io/name: robot-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: robot-api
data:
  shelves.csv: |
    {{- .Values.robotApi.shelvesCsv | nindent 4 }}
