{{- range $dc := .Values.centers }}
{{- $root := $ }}
{{- $svcName := include "adc.dc.serviceName" (dict "root" $root "dc" $dc "component" "robot-api") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svcName }}
  labels:
    {{- include "adc.commonLabels" $root | nindent 4 }}
    app.kubernetes.io/name: robot-api
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/component: robot-api
    distribution-center: {{ $dc.name }}
spec:
  selector:
    app.kubernetes.io/name: robot-api
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    distribution-center: {{ $dc.name }}
  ports:
    - name: http
      port: {{ $dc.robotApi.port }}
      targetPort: http
{{- end }}
