{{- $svcName := include "adc.distributionCenter.serviceName" (dict "root" $ "component" "shipping-api") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svcName }}
  labels:
    {{- include "adc.commonLabels" . | nindent 4 }}
    app.kubernetes.io/name: shipping-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: shipping-api
spec:
  selector:
    app.kubernetes.io/name: shipping-api
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.shippingApi.port }}
      targetPort: http
