{{- range $dc := .Values.centers }}
{{- $root := $ }}
{{- $cmName := printf "%s-%s-wms-inventory" (include "adc.fullname" $root) $dc.name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cmName }}
  labels:
    {{- include "adc.commonLabels" $root | nindent 4 }}
    app.kubernetes.io/name: wms-api
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/component: wms-api
    distribution-center: {{ $dc.name }}
data:
  inventory.csv: |
    {{- $dc.wmsApi.inventoryCsv | nindent 4 }}
{{- end }}
