{{- $cmName := printf "%s-wms-inventory" (include "adc.fullname" $) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cmName }}
  labels:
    {{- include "adc.commonLabels" . | nindent 4 }}
    app.kubernetes.io/name: wms-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: wms-api
data:
  inventory.csv: |
    {{- .Values.wmsApi.inventoryCsv | nindent 4 }}
