FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src
COPY data ./data

ENV HOST=0.0.0.0
ENV PORT=8001
ENV LOCATION_NAME=DC-VIRTUAL-01
ENV INVENTORY_CSV_PATH=data/inventory.csv
EXPOSE 8001

CMD ["python", "-m", "src"]
