pipeline
{
   agent any

   options
   {
      disableConcurrentBuilds()
      buildDiscarder(logRotator(numToKeepStr: '1'))
   }

   stages
   {
      stage('Prepare')
      {
         steps
         {
            sh '''
                    echo "PATH = ${PATH}"
                '''

            git branch: 'main',
                url: 'https://github.com/glroland/dc-agent.git'
         }
      }

      stage('Create Docker Image for po-ingest-api')
      {
         steps
         {
            sh 'cd po-ingest-api ; docker build --no-cache -f Containerfile . --tag po-ingest-api:$BUILD_NUMBER'
            sh 'cd po-ingest-api ; docker save po-ingest-api:$BUILD_NUMBER > po-ingest-api-dockerimage.tar'
            step(followSymlinks: false, artifacts: 'po-ingest-api/po-ingest-api-dockerimage.tar', $class: 'ArtifactArchiver')
            sh 'cd po-ingest-api ; docker rmi po-ingest-api:$BUILD_NUMBER'
         }
      }

      stage('Reload then push images to quay')
      {
         steps
         {
            script
            {
               docker.withRegistry('https://registry.home.glroland.com/', 'quay')
               {
                  sh 'docker load -i po-ingest-api/po-ingest-api-dockerimage.tar'
                  sh 'docker tag po-ingest-api:$BUILD_NUMBER registry.home.glroland.com/distribution-center/po-ingest-api:$BUILD_NUMBER'
                  sh 'docker rmi po-ingest-api:$BUILD_NUMBER'
                  sh 'docker push registry.home.glroland.com/distribution-center/po-ingest-api:$BUILD_NUMBER'
                  sh 'docker rmi registry.home.glroland.com/distribution-center/po-ingest-api:$BUILD_NUMBER'
               }
            }
         }
      }
   }
}
