{{- if and .Values.enabled .Values.global.openshift.routes.enabled .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "adc.labelGeneratorApi.serviceName" . }}
  labels:
    {{- include "adc.commonLabels" . | nindent 4 }}
    app.kubernetes.io/name: label-generator-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: label-generator-api
spec:
  to:
    kind: Service
    name: {{ include "adc.labelGeneratorApi.serviceName" . }}
  port:
    targetPort: http
  tls:
    termination: {{ .Values.global.openshift.routes.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.global.openshift.routes.tls.insecureEdgeTerminationPolicy }}
{{- end }}
