FROM registry.redhat.io/rhai/base-image-cpu-rhel9:3.5.0-1786556387

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src
COPY data ./data

ENV HOST=0.0.0.0
ENV PORT=8090
EXPOSE 8090

CMD ["python", "-m", "src"]
